config/routes.rb
ActiveTest::Application.routes.draw do
  devise_for :users
  resources :users
resources :tags
  resources :albums do
   resources :tags
  end
  resources :photos do
   resources :tags
   
  end
  resources :users do
  resources :albums
end
  resources :users do
  resources :albums do
  resources :photos
  end
end
  resources :albums do
  resources :photos
end

   root :to => 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :tags, :as => :taggable



end

app/models/photo.rb
class Photo < ActiveRecord::Base
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
belongs_to :album
has_many :tags, :as => :taggable
end

app/models/tag.rb
class Tag < ActiveRecord::Base
belongs_to :taggable, :polymorphic => true
  before_create :check_user
  def check_user
    @user = User.find_by_email(self.name)
    if @user
     self.user_id = @user
     return true
    else
     return false
    end
  end
def join_tags
   raise "yes"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

 has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
def index
@albums = current_user.albums 
end
def new
@album = Album.new
@user = User.find(current_user.id)
end
def create
    @album = current_user.albums.create(params[:album])
    @album.save
    redirect_to user_album_path(:user_id =>current_user.id, :id => @album.id)
end
def show
@album = Album.find(params[:id])
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.create(params[:photo])
    redirect_to user_album_path(:user_id =>current_user.id, :id => @album.id)
  end
  def show
   @photo = Photo.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
  if params[:photo_id]
   
   @tag = Tag.create(params[:tag])

   @photo = Photo.find(params[:photo_id])    
   redirect_to  user_album_photo_path(:user_id => current_user.id, :album_id =>@photo.album_id , :id => params[:photo_id])

  end
  if params[:album_id]
   @tag = Tag.create(params[:tag])
   redirect_to user_album_path(:user_id => current_user.id, :id => params[:album_id])
  end
  end
 def index
   @tags = Tag.where("user_id = ?", params[:id])
#raise @tags.inspect
 end

def destroy
    raise "yes"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
@users=User.all
end
def show
render :text => "signed off"
current_user.id=nil
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_filter :authenticate_user!

def index
end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/index.html.erb
<hr>
<% @albums.each do |u| %>
<br />
<%= link_to "Album "+u.name,  user_album_path(:user_id =>current_user.id, :id => u.id) %>
<% end %>

app/views/albums/new.html.erb
<h2>Create a new album:</h2>
<%= form_for([@user, @user.albums.build]) do |f| %>
<br />
    <%= f.label :name %>
<br />
    <%= f.text_field :name %>
<br />
    <%= f.submit %>

<% end %>

app/views/albums/show.html.erb
<br />
Name:
<br />
<%= @album.name %>
<br/>
<hr />
<br />
list of photos

<%= render @album.photos %>

<h2>Add a photo:</h2>
<%= render "photos/new" %>
<br />
  <%= render :partial => 'tags/tag', :locals => { :tag => @album }  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActiveTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%#= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/photos/_new.html.erb
<%= form_for([@album, @album.photos.build]) do |f| %>
 
Photo<br />

<%= f.file_field :image %>
<br />
    <%= f.submit %>

<br />
<% end %>

app/views/photos/_photo.html.erb
<br />
<%= link_to (image_tag photo.image.url(:thumb)), user_album_photo_path(:user_id => current_user.id, :album_id => @album.id, :id => photo.id) %>
<br />

app/views/photos/show.html.erb
<%= image_tag(@photo.image.url)  %>

  <%= render :partial => 'tags/tag', :locals => { :tag => @photo }  %>

app/views/tags/_tag.html.erb
<br />
<br />
<p>
  <b>Tags:</b><br/>
  <% tag.tags.each do |t|%>
    <input type ="text" value = <%= t.name %> > <%= link_to "delete" , tag_path(:user_id => current_user.id, :album_id =>@photo.album_id , :photo_id => params[:photo_id])
 %><br/>
   <% end %>
</p>


<%= form_for([tag, Tag.new()]) do |f| %>

Add tag

  <%= f.text_field :name %>
  <%= f.hidden_field :taggable_id, :value => tag.id %>
<%= f.hidden_field :taggable_type, :value => tag.class %>

<br />
  <%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<hr>
The user is tagged in following
<hr />
<% @tags.each do |u| %>
<br />
<% if u.taggable_type == "Photo" %>
Image
<br />
<%= image_tag(Photo.find(u.taggable.id).image.url)  %>
<br />
<% end %>
<% if u.taggable_type == "Album" %>
Album name:
<br />
<%= Album.find(u.taggable_id).name %>
<br />
<% end %>

<% end %>

app/views/users/index.html.erb
<hr>
<% @users.each do |u| %>
<br />
<%= link_to u.email, tags_path(:id => u.id) %>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "List of users", users_path %>
<%= link_to "New album", new_album_path %>
<%= link_to "List of albums", albums_path %>